---

- name: set facts
  set_fact:
    perfrom_action: true
    role_comment: "( {{ role_path|basename }} )"

- name: set createRepository script name
  set_fact:
    script_filename: "{{ nexus_script }}-{{ ansible_date_time.iso8601_micro | to_uuid }}"

- name: upload templated script {{ script_filename }}
  uri:
    url: "{{ nexus_url_api_script }}"
    method: "POST"
    user: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    force_basic_auth: "true"
    body:
      name: "{{ script_filename }}"
      content: "{{ lookup('file', './files/scripts/' + nexus_script + '.groovy') }}"
      type: "groovy"
    body_format: "json"
    return_content: "true"
    status_code: 204
    timeout: 5
  register: nexus_script_create
  delay: "{{ wait_delay | default(5) }}"

- name: run uploaded script {{ script_filename }}
  uri:
    url: "{{ nexus_url_api_script }}/{{ script_filename }}/run"
    method: "POST"
    user: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    force_basic_auth: "true"
    headers:
      Content-Type: "text/plain"
    body: "{{ service_nexus_script_arguments | to_json }}"
    timeout: 5
    status_code: 200
  register: nexus_script_run
  delay: "{{ wait_delay | default(5) }}"

- name: delete uploaded script {{ script_filename }}
  uri:
    url: "{{ nexus_url_api_script }}/{{ script_filename }}"
    method: "DELETE"
    user: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    force_basic_auth: "true"
    timeout: 5
    status_code: 204
  register: nexus_script_delete
  delay: "{{ wait_delay | default(5) }}"
