---

- set_fact:
    perfrom_action: yes
    role_comment: "( {{role_path|basename}} )"

- name: perform nexus api action {{ role_comment }}
  debug:
    msg:
      - "{{ api_action }}"
      - "{{ body }}"

- name: wait for nexus service {{ role_comment }}
  wait_for:
    host: "{{ nexus_host }}"
    port: "{{ nexus_port }}"
    delay: "{{ wait_delay | default(5) }}"


- name: wait until nexus service is ready {{ role_comment }}
  uri:
    url: "http://{{ nexus_host }}:{{ nexus_port }}"
    return_content: yes
    timeout: 300
  register: nexus_console
  until: nexus_console.content.find("Nexus Repository Manager") != -1
  delay: "{{ wait_delay | default(5) }}"
  retries: 360

- name: check if repo already is available {{ role_comment }}
  uri:
    url: "{{ repo_check_url }}"
    return_content: yes
    timeout: 3
  register: docker_registry_ping
  ignore_errors: yes
  when:
    - api_action is defined and api_action == 'createrepo'

- name: check if repo already is available output
  debug:
    msg: "{{ docker_registry_ping }}"
  no_log: "{{ debug_hide }}"

- name: nexus registry already exist {{ role_comment }}
  debug:
    msg: "registry exist"
  when:
    - api_action is defined and api_action == 'createrepo'
    - not docker_registry_ping.failed

- name: nexus registry does not exist {{ role_comment }}
  set_fact:
    perfrom_action: "{{ docker_registry_ping.failed }}"
  when:
    - api_action is defined and api_action == 'createrepo'
    - docker_registry_ping.failed

- name: login into nexus {{ role_comment }}
  debug:
    msg: "username={{ nexus_username | b64encode | urlencode() }}&password={{ nexus_password | b64encode | urlencode() }}"
  when: perfrom_action

- name: login into nexus {{ role_comment }}
  uri:
    url: "{{ nexus_api_login_url }}"
    headers:
      Content-Type: "application/x-www-form-urlencoded"
      Origin: "https://{{ nexus_host }}:{{ nexus_port }}"
    method: POST
    body_format: raw
    body: "username={{ nexus_username | b64encode | urlencode() }}&password={{ nexus_password | b64encode | urlencode() }}"
    return_content: yes
    status_code: 204
    timeout: 3
  register: nexus_login_result
  when: perfrom_action

- name: nexus login result {{ role_comment }}
  debug:
    msg: "{{ nexus_login_result }}"
  when: perfrom_action

- set_fact:
    nexus_cookie: "{{ nexus_login_result.set_cookie }}"
  when: perfrom_action

- name: nexus login cookie {{ role_comment }}
  debug:
    msg: "{{ nexus_cookie }}"
  when: perfrom_action

- name: nexus api url {{ role_comment }}
  debug:
    msg: "{{ nexus_api_url }}"
  when: perfrom_action

- name: post to api repo {{ role_comment }}
  uri:
    url: "{{ nexus_api_url }}"
    headers:
      Origin: "https://{{ nexus_host }}:{{ nexus_port }}"
      Content-Type: "application/json"
      Cookie: "{{ nexus_cookie }}"
    method: POST
    body_format: json
    body: "{{ body }}"
    return_content: yes
  register: createrepo_result
  when: perfrom_action

- name: nexus create repo result {{ role_comment }}
  debug:
    msg: "{{ createrepo_result }}"
  when: perfrom_action

- name: nexus create repo outcome {{ role_comment }}
  debug:
    msg: "Could not create repo: {{ createrepo_result.json.result.errors.name }}"
  when:
    - perfrom_action
    - createrepo_result.json is defined
    - createrepo_result.json.result is defined
    - createrepo_result.json.result.success is defined
    - not createrepo_result.json.result.success
