---
- name: Converge
  hosts: instance
  become: true
  vars:
    local_role_name: "ansible-role-nexus-api"
    role_name: "{% if lookup('env','ROLE_NAME_FULL') %}{{ lookup('env','ROLE_NAME_FULL') }}{% else %}{{ local_role_name }}{% endif %}"
    docker_nexus_container: "nexustest"
    test_service_nexus_port: "10081"
    test_service_nexus_username: "admin"
    test_service_nexus_password: "admin123"
    test_nexus_container_name: "{{ local_role_name }}-test-nexus"

  pre_tasks:
    - name: get docker host ip
      become: true
      shell: |
        set -o pipefail
        /sbin/ip route | awk '/default/ { print $3 }'
      args:
        executable: /bin/bash
      register: dockerhost_ip
      changed_when: false

  tasks:
    - name: setup nexus
      import_role:
        name: "aem_design.nexus"
      vars:
        service_nexus_host: "{{ dockerhost_ip.stdout }}"
        docker_container_name: "{{ test_nexus_container_name }}"
        docker_volumes: []
        debug_hide: "false"
        service_nexus_port: "{{ test_service_nexus_port }}"
        service_nexus_user: "{{ test_service_nexus_username }}"
        service_nexus_password: "{{ test_service_nexus_password }}"
        service_nexus_registry_port: "10000"
        service_nexus_registry_mirror_port: "10001"
        service_nexus_registry_group_port: "10002"
        service_nexus_maven_repository_port: "10081"
        docker_published_ports: [
          "10000:5000",
          "10081:8080",
          "10001:5001",
          "10002:5002"
        ]
        docker_host: "unix://tmp/docker.sock"
    - name: create nexus repo
      import_role:
        name: "{{ role_name }}"
      vars:
        service_nexus_host: "{{ dockerhost_ip.stdout }}"
        service_nexus_port: "{{ test_service_nexus_port }}"
        service_nexus_user: "{{ test_service_nexus_username }}"
        service_nexus_password: "{{ test_service_nexus_password }}"
        service_nexus_script: "createRepository"
        service_nexus_script_arguments: [
          {
            "blob_store": "default",
            "format": "maven2",
            "layout_policy": "permissive",
            "maximum_component_age": -1,
            "maximum_metadata_age": 1440,
            "name": "central",
            "negative_cache_enabled": true,
            "negative_cache_ttl": 1440,
            "remote_url": "https://repo1.maven.org/maven2/",
            "strict_content_validation": true,
            "type": "proxy",
            "version_policy": "release",
            "write_policy": "allow_once"
          },
          {
            "blob_store": "default",
            "format": "maven2",
            "layout_policy": "strict",
            "maximum_component_age": -1,
            "maximum_metadata_age": 1440,
            "name": "private-release",
            "negative_cache_enabled": true,
            "negative_cache_ttl": 1440,
            "strict_content_validation": true,
            "type": "hosted",
            "version_policy": "release",
            "write_policy": "allow_once"
          },
          {
            "blob_store": "default",
            "format": "maven2",
            "layout_policy": "strict",
            "maximum_component_age": -1,
            "maximum_metadata_age": 1440,
            "member_repos": [
              "central",
              "jboss"
            ],
            "name": "public",
            "negative_cache_enabled": true,
            "negative_cache_ttl": 1440,
            "strict_content_validation": true,
            "type": "group",
            "version_policy": "release",
            "write_policy": "allow_once"
          },
          {
            "blob_store": "default",
            "force_basic_auth": true,
            "format": "docker",
            "http_port": 9081,
            "index_type": "HUB",
            "layout_policy": "strict",
            "maximum_component_age": 1440,
            "maximum_metadata_age": 1440,
            "name": "docker-proxy",
            "negative_cache_enabled": true,
            "negative_cache_ttl": 1440,
            "remote_url": "https://registry-1.docker.io",
            "strict_content_validation": true,
            "type": "proxy",
            "use_nexus_certificates_to_access_index": false,
            "v1_enabled": true,
            "version_policy": "release",
            "write_policy": "allow_once"
          },
          {
            "blob_store": "default",
            "force_basic_auth": true,
            "format": "docker",
            "http_port": 9080,
            "layout_policy": "strict",
            "maximum_component_age": 1440,
            "maximum_metadata_age": 1440,
            "name": "docker-hosted",
            "negative_cache_enabled": true,
            "negative_cache_ttl": 1440,
            "strict_content_validation": true,
            "type": "hosted",
            "v1_enabled": true,
            "version_policy": "release",
            "write_policy": "allow_once"
          },
          {
            "blob_store": "default",
            "force_basic_auth": true,
            "format": "docker",
            "http_port": 9082,
            "layout_policy": "strict",
            "maximum_component_age": 1440,
            "maximum_metadata_age": 1440,
            "member_repos": [
              "docker-hosted",
              "docker-proxy"
            ],
            "name": "docker-group",
            "negative_cache_enabled": true,
            "negative_cache_ttl": 1440,
            "strict_content_validation": true,
            "type": "group",
            "v1_enabled": true,
            "version_policy": "release",
            "write_policy": "allow_once"
          },
          {
            "blob_store": "default",
            "format": "pypi",
            "layout_policy": "strict",
            "maximum_component_age": 1440,
            "maximum_metadata_age": 1440,
            "name": "pypi",
            "negative_cache_enabled": true,
            "negative_cache_ttl": 1440,
            "remote_url": "https://pypi.python.org/",
            "strict_content_validation": true,
            "type": "proxy",
            "version_policy": "release",
            "write_policy": "allow_once"
          },
          {
            "blob_store": "default",
            "format": "pypi",
            "layout_policy": "strict",
            "maximum_component_age": -1,
            "maximum_metadata_age": 1440,
            "name": "pypi-internal",
            "negative_cache_enabled": true,
            "negative_cache_ttl": 1440,
            "strict_content_validation": true,
            "type": "hosted",
            "version_policy": "release",
            "write_policy": "allow"
          },
          {
            "blob_store": "default",
            "format": "pypi",
            "layout_policy": "strict",
            "maximum_component_age": -1,
            "maximum_metadata_age": 1440,
            "member_repos": [
              "pypi-internal",
              "pypi"
            ],
            "name": "pypi-all",
            "negative_cache_enabled": true,
            "negative_cache_ttl": 1440,
            "strict_content_validation": true,
            "type": "group",
            "version_policy": "release",
            "write_policy": "allow_once"
          },
        ]
